#!/bin/bash

# Ensure the script is run as sudo
if [ "$EUID" -ne 0 ]; then
    echo "Re-running with sudo..."
    exec sudo "$0" "$@"
    exit 1
fi

# Copy burn binary to /bin
cp ./data/burn /bin
echo "Copied ./data/burn to /bin/"

# Apply execution permissions
chmod +x /bin/burn
echo "Applied +x permissions to /bin/burn"

# Done message
echo "Done! Run 'burn -h' to seek help for burn."
